CREATE TABLE usuarios (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    -- columna email según la referencia RFC5321
    correo VARCHAR(254) UNIQUE NOT NULL,
    nombre_completo VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    CONSTRAINT longitud_nombre_completo CHECK (char_length(nombre_completo) >= 5)
);

CREATE TABLE intentos_signin (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(254) UNIQUE NOT NULL,
    conteo_intentos INT DEFAULT 0 NOT NULL,
    tiempo_bloqueo TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE manejo_sessions (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    -- session_id guardará el identificador único de sesión
    session_id TEXT NOT NULL,
    ultima_actividad TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE OR REPLACE FUNCTION nuevo_usuario()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.usuarios(id, correo, nombre_completo)
  VALUES (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'nombre_completo', 'Usuario')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION nuevo_usuario();